# Generated by Django 2.2.2 on 2019-06-19 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=20)),
                ('contractor', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_hrs', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
