# Generated by Django 2.2.2 on 2019-06-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=250, unique=True)),
                ('contractor', models.CharField(blank=True, max_length=250)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_hrs', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
