# Generated by Django 2.2.2 on 2019-06-15 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
